//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.34014
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BellLib.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BellLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;BCO_1.7.10&gt;
        ///  &lt;Info&gt;
        ///    &lt;Latest&gt;1.0.0&lt;/Latest&gt;
        ///    &lt;Recommended&gt;1.0.0&lt;/Recommended&gt;
        ///    &lt;Down&gt;http://bellsoft.iptime.org:4135/FileServer/BSL/Option/BCO_1.7.10/&lt;/Down&gt;
        ///  &lt;/Info&gt;
        ///  &lt;Version&gt;
        ///    &lt;Ver&gt;1.0.0&lt;/Ver&gt;
        ///  &lt;/Version&gt;
        ///&lt;/BCO_1.7.10&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BCO_1_7_10 {
            get {
                return ResourceManager.GetString("BCO_1_7_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;BCO_1.7.10&gt;
        ///  &lt;Option&gt;
        ///    &lt;Opt Name=&quot;NEI&quot; MUID=&quot;NEI&quot; Default=&quot;true&quot;/&gt;
        ///    &lt;Opt Name=&quot;MapWriter&quot; MUID=&quot;MiniMap&quot; Default=&quot;false&quot;/&gt;
        ///    &lt;Opt Name=&quot;Rei&apos;s MiniMap&quot; MUID=&quot;MiniMap&quot; Default=&quot;false&quot;/&gt;
        ///  &lt;/Option&gt;
        ///  &lt;Directory&gt;
        ///    &lt;Dir&gt;mods&lt;/Dir&gt;
        ///    &lt;Dir&gt;flan&lt;/Dir&gt;
        ///  &lt;/Directory&gt;
        ///  &lt;Hash&gt;
        ///    &lt;File Name=&quot;NEI&quot; loc=&quot;mods\NEI.jar&quot;&gt;파일 해시 asdfasdf&lt;/File&gt;
        ///    &lt;File Name=&quot;MapWriter&quot; loc=&quot;mods\MapWriter.jar&quot;&gt;파일 해시 asdfasdf&lt;/File&gt;
        ///    &lt;File Name=&quot;Rei&apos;s MiniMap&quot; loc=&quot;mo[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BCO_1_7_10_1_0_0 {
            get {
                return ResourceManager.GetString("BCO_1_7_10_1_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;BCP_1.7.10&gt; &lt;!-- BellCraft Pack --&gt;
        ///  &lt;Info&gt;
        ///    &lt;Latest&gt;1.0.0&lt;/Latest&gt;
        ///    &lt;Recommended&gt;1.0.0&lt;/Recommended&gt;
        ///    &lt;Down&gt;http://bellsoft.iptime.org:4135/FileServer/BSL/Base/BCP_1.7.10/&lt;/Down&gt;
        ///  &lt;/Info&gt;
        ///  &lt;Version&gt;
        ///    &lt;Ver&gt;1.0.0&lt;/Ver&gt;
        ///  &lt;/Version&gt;
        ///&lt;/BCP_1.7.10&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BCP_1_7_10 {
            get {
                return ResourceManager.GetString("BCP_1_7_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;BCP_1.7.10&gt;
        ///  &lt;Directory&gt;
        ///    &lt;Dir&gt;assets&lt;/Dir&gt;
        ///    &lt;Dir&gt;resource&lt;/Dir&gt;
        ///  &lt;/Directory&gt;
        ///  &lt;Hash&gt;
        ///    &lt;File loc=&quot;assets\어쩌구저쩌구.txt&quot;&gt;파일 해시 asdfasdf&lt;/File&gt;
        ///    &lt;File loc=&quot;assets\이러쿵저러쿵.log&quot;&gt;파일 해시 asdfasdf&lt;/File&gt;
        ///    &lt;File loc=&quot;resource\리소스.txt&quot;&gt;파일 해시 asdfasdf&lt;/File&gt;
        ///  &lt;/Hash&gt;
        ///&lt;/BCP_1.7.10&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BCP_1_7_10_1_0_0 {
            get {
                return ResourceManager.GetString("BCP_1_7_10_1_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;BellCraft8&gt;
        ///  &lt;Info&gt;
        ///    &lt;Activation&gt;TRUE&lt;/Activation&gt;
        ///    &lt;Name&gt;방울크래프트&lt;/Name&gt;
        ///    &lt;Recommended&gt;8.5.0&lt;/Recommended&gt;
        ///    &lt;Latest&gt;8.8.0&lt;/Latest&gt;
        ///    &lt;Base&gt;Forge_1.7.10&lt;/Base&gt;
        ///    &lt;Option&gt;BCO_1.7.10&lt;/Option&gt;
        ///  &lt;/Info&gt;
        ///  &lt;Detail&gt;
        ///    &lt;Info Name=&quot;Multi Play Pack&quot;&gt;TRUE&lt;/Info&gt;
        ///    &lt;Info Name=&quot;Minecraft Version&quot;&gt;1.7.10&lt;/Info&gt;
        ///  &lt;/Detail&gt;
        ///  &lt;Permission&gt;
        ///    &lt;User ID=&quot;bell04204@gmail.com&quot;&gt;2&lt;/User&gt;
        ///  &lt;/Permission&gt;
        ///  &lt;Server&gt;
        ///    &lt;UID&gt;SangDolE&lt;/UID&gt;
        ///    &lt;UID&gt;Be[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BellCraft8 {
            get {
                return ResourceManager.GetString("BellCraft8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;BellCraft&gt;
        ///  &lt;Version&gt;
        ///    &lt;Option&gt;Latest&lt;/Option&gt;
        ///    &lt;Base&gt;Recommended&lt;/Base&gt;
        ///  &lt;/Version&gt;
        ///
        ///  &lt;Directory&gt;
        ///    &lt;Dir&gt;config&lt;/Dir&gt;
        ///    &lt;Dir&gt;mods&lt;/Dir&gt;
        ///    &lt;Dir&gt;flan&lt;/Dir&gt;
        ///  &lt;/Directory&gt;
        ///  &lt;Hash&gt;
        ///    &lt;File loc=&quot;mods\buildcraft.jar&quot;&gt;asasdfasdfasdf파일해시&lt;/File&gt;
        ///    &lt;File loc=&quot;mods\industrialcraft.jar&quot;&gt;asasddffasdfasdf파일해시&lt;/File&gt;
        ///    &lt;File loc=&quot;mods\appliedenergetics2.jar&quot;&gt;asasdfasdfaasdfwaesdf파일해시&lt;/File&gt;
        ///  &lt;/Hash&gt;
        ///&lt;/BellCraft&gt;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string BellCraft8_8_8_0 {
            get {
                return ResourceManager.GetString("BellCraft8_8_8_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap Logo_BSN1 {
            get {
                object obj = ResourceManager.GetObject("Logo_BSN1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap Logo_BSN1_1 {
            get {
                object obj = ResourceManager.GetObject("Logo_BSN1_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap Logo_BSN2 {
            get {
                object obj = ResourceManager.GetObject("Logo_BSN2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Bitmap Logo_BSN3 {
            get {
                object obj = ResourceManager.GetObject("Logo_BSN3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Icon Photo_Bell {
            get {
                object obj = ResourceManager.GetObject("Photo_Bell", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Icon Photo_Random {
            get {
                object obj = ResourceManager.GetObject("Photo_Random", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.Drawing.Icon Photo_RedBell {
            get {
                object obj = ResourceManager.GetObject("Photo_RedBell", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   System.IO.MemoryStream과(와) 유사한 System.IO.UnmanagedMemoryStream 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream Sound_alarm {
            get {
                return ResourceManager.GetStream("Sound_alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.IO.MemoryStream과(와) 유사한 System.IO.UnmanagedMemoryStream 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream Sound_end {
            get {
                return ResourceManager.GetStream("Sound_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.IO.MemoryStream과(와) 유사한 System.IO.UnmanagedMemoryStream 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream Sound_error {
            get {
                return ResourceManager.GetStream("Sound_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.IO.MemoryStream과(와) 유사한 System.IO.UnmanagedMemoryStream 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream Sound_select {
            get {
                return ResourceManager.GetStream("Sound_select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.IO.MemoryStream과(와) 유사한 System.IO.UnmanagedMemoryStream 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream Sound_start {
            get {
                return ResourceManager.GetStream("Sound_start", resourceCulture);
            }
        }
    }
}
